Фикс перетаскивания точек
2gis/mapgl-ruler pull request #21
Opened 2022-09-19 13:33 UTC by itanka9

Поля `clientX` и `clientY` требуют дополнительной обработки, так как они возвращают координаты относительно вьюпорта окна браузера, а необходимо использовать координаты относительно контейнера карты.

Проблему можно пронаблюдать, например, вот здесь https://vetchka.ru/snippets/17499/edit Достаточно попробовать перетащить одну из точек - во время перетаскивания она будет позиционироваться неверно.

Для фикса я перенес и использовал функцию `getMousePosition` из нашего движка.

2022-09-29 13:53 UTC, Farfurix requested changes

2022-09-29 13:53 UTC, Farfurix commented on src/utils.ts
> +    const rect = container.getBoundingClientRect();
NOTE: all the screencasts above have another the constant displacement issue. Pay attention only to the movement of the ruler joints.

The mouse position issue is still persist if we change additional CSS as
```diff
  #container {
+     padding: 30px;
-     position: absolute;
-     top: 30px;
-     left: 30px;
-     margin: 0;
-     width: calc(100% - 60px);
-     height: calc(100% - 60px);
-     overflow: hidden;
  }
```
CSS change result:

https://user-images.githubusercontent.com/30019338/193046760-5f17bdfb-3699-42dd-9ff5-a159d8bae22c.mp4

Here we have to base on the nested `canvas` element:
```js
// Or we can use here some `children` logic
const rect = container.querySelector('canvas')!.getBoundingClientRect();
```
CSS + rect changes result:

https://user-images.githubusercontent.com/30019338/193047806-43b182ee-86f3-428e-9460-5758c4a88e67.mp4

2022-11-01 09:19 UTC, kalyanov approved these changes

2022-11-01 09:27 UTC, Farfurix approved these changes

2022-11-01 14:52 UTC, merged