Апи редактирования площадников
2gis/mapgl-ruler pull request #7
Opened 2022-04-11 08:12 UTC by ok-go

- Добавил режимы работы: режим линейки для замера растояния и режим для редактирования полигона и вычисления его площади, периметра.
- вынес стили в отдельный файл. в отдельной задаче будет реализация кастомизации.
- метод получения построенной геометрии для двух режимов
- получение построенной геометрии в событии change 
- инициализация списком точек для построения геометрии

  рефакторинг:
- вынес в отдельные сущности рисование полилайна, площадника, превью-линии (упростил логику отрисовки в Ruler.update)
- удалил лишнюю логику показа\сокрытия snap-точки
- занусул флаги рулетки в один объект 
-

2022-04-11 16:56 UTC, alxart commented on src/constants.ts
>  export const jointRemoveBtnSvg =
Смысла в этом файле больше нет: `jointRemoveBtnSvg` используется только в одном месте, можно туда и перенести.

2022-04-12 03:37 UTC, alxart commented on src/area.ts
> +export class Area {
```
 * @hidden
 * @internal
```
?

2022-04-12 03:39 UTC, alxart commented on src/polyline.ts
> +export class Polyline extends Evented<EventTable> {
```
 * @hidden
 * @internal
```
?

2022-04-12 04:41 UTC, alxart commented on src/ruler.ts
> +     * Set ruler's behaviour. Measuring the distance of a polyline or the area of polygon.
```suggestion
     * Sets ruler's behavior. Specifies whether the ruler should be in measuring mode of the distance of a polyline or the area of polygon.
```

2022-04-12 08:17 UTC, alxart commented on src/polyline.ts
> +export class Polyline extends Evented<EventTable> {
👌

2022-04-12 08:38 UTC, ok-go commented on src/ruler.ts
> +export type RulerMode = 'polyline' | 'polygon';
нет, не точно. поправил на distance\area.

2022-04-12 16:13 UTC, kalyanov requested changes

2022-04-12 16:17 UTC, kalyanov requested changes

2022-04-12 16:17 UTC, kalyanov commented on src/area.ts
> +        this.area = 0;
Кажется ты сейчас площадь вообще нигде не считаешь

2022-04-13 07:31 UTC, ok-go commented on src/utils.ts
> +export function getPolygonCentroid(points: GeoPoint[]): GeoPoint {
еще не решил. пока метод просто остался от прототипа, будет переделан в задаче вместе с расчетом площади.

2022-04-13 07:32 UTC, ok-go commented on src/area.ts
> +        return `${this.area} m&#178;`;
отображение и расчеты площади будут в отдельной задаче, это от прототипа осталось.

2022-04-13 07:36 UTC, ok-go commented on src/ruler.ts
> +export type RulerMode = 'distance' | 'area';
не вижу проблемы ни в одном из способов именования. @alxart ты был за текущий вариант, мб есть что сказать по поводу предложения Олега

2022-04-13 07:37 UTC, ok-go commented on src/ruler.ts
> +    private readonly redrawFlags: RedrawFlags;
сам объект то не пересоздается. idea настаивает что readonly

2022-04-13 07:39 UTC, alxart commented on src/style.ts
> +const maxPhase = 2147483647; // max zIndex in CSS (2 ** 31 - 1).
Тут дело не в связывании WebGL и CSS, а то, что это число максимально для CSS и достаточно большое для WebGL, хотя туда можно и больше запаковать, но нужно ли?

2022-04-13 07:45 UTC, alxart commented on src/ruler.ts
> +export type RulerMode = 'distance' | 'area';
Это же режим работы линейки, который задает пользователь. Кажется, что режимы именно измерения "дистанции" и "площади" понятнее, чем то, что мы будем рисовать - "линия" и "полигон".

2022-04-13 07:46 UTC, ok-go commented on src/ruler.ts
>   * The list of events that can be emitted by a Ruler instance.
'redraw' будет внутренним событием - оно было добавлено что бы в тестах ловить момент когда нарисовали измененния.
`change`- событие отображает изменение состояния линейки. добавлено что бы через апи можно было понять что произошли какие-то изменения в рулетке - добавилась\удалилась\изменилась точка или точки. Возможно стоит удалить из события кучу данных и пользователь будет после события получать их по мере необходимости через методы

2022-04-13 07:46 UTC, alxart commented on src/ruler.ts
> +export type RulerMode = 'distance' | 'area';
В общем, дело в контексте.

2022-04-13 07:56 UTC, ok-go commented on src/utils.ts
> +export function getArea(map: mapgl.Map, points: GeoPoint[]): mapgl.Polygon {
может) поправлю

2022-04-13 07:58 UTC, ok-go commented on src/utils.ts
> +        anchor: [-jointTotalWidth, height / 2],
поправлю. осталось от экспериментов

2022-04-13 14:22 UTC, ok-go commented on src/ruler.ts
> +export type RulerMode = 'distance' | 'area';
кажется развиваться плагин если и будет то в сторону рисовальщика с возможностью доп. вычислений. давайте остановимся на варианте режимов polyline/polygon, как режимы способа рисования.

2022-04-14 08:35 UTC, kalyanov commented on src/style.ts
> +const maxPhase = 2147483647; // max zIndex in CSS (2 ** 31 - 1).
Наброс не про конкретное значение, а про то, что сейчас одна переменнная, что как бы наталкивает на мысль что все это свзяано, но нет. Фаза для вебгл и цсс зет-индекс — не пересекающиеся штуки, а значит и в коде должны быть заданы отдельно, чтобы не наводить смуту

2022-04-14 08:37 UTC, kalyanov commented on src/utils.ts
> +export function getPolygonCentroid(points: GeoPoint[]): GeoPoint {
гут, не забыть бы) Просто на ревью площадей этот момент не подсветится в коде, если ты тут ничего не поменяешь

2022-04-14 08:38 UTC, ok-go commented on src/style.ts
> +const maxPhase = 2147483647; // max zIndex in CSS (2 ** 31 - 1).
давай это замечание укажу в задаче на стилизацию, все равно тут будут какие-то изменения вноситься.

2022-04-14 08:40 UTC, kalyanov commented on src/utils.ts
> +        anchor: [-jointTotalWidth, height / 2],
Где поправишь? Хорошо бы такие моменты тудухами помечать, чтобы вопросов не возникало

2022-04-14 08:42 UTC, ok-go commented on src/utils.ts
> +export function getPolygonCentroid(points: GeoPoint[]): GeoPoint {
изменения уже в процессе в задаче на расчет площади) не забыл

2022-04-14 08:45 UTC, ok-go commented on src/utils.ts
> +        anchor: [-jointTotalWidth, height / 2],
в этом ревью - уже поправил. +2 добавлять нет смысла - там надписи начинуют залазить на точки.

2022-04-14 10:24 UTC, kalyanov commented on src/utils.ts
> +    interactive: boolean,
Коммент проигнорирован

2022-04-14 10:25 UTC, kalyanov commented on src/types.ts
> +    lengths: number[];
и этот проигнорен

2022-04-14 10:45 UTC, ok-go commented on src/types.ts
> +    lengths: number[];
там длины линейки на каждом из узлов. что бы всю длину получить достаточно обратиться к последнему элементу.

в полигон добавлю, ок

2022-04-14 10:46 UTC, ok-go commented on src/utils.ts
> +    interactive: boolean,
ок. действительно пора

2022-04-14 10:53 UTC, ok-go commented on src/types.ts
>  export interface ChangeEvent {
таких интерфейсов уже нет и получение данных объеденены в один метод getData.

из типа события видно что может быть либо инфо полигона, либо линии - кажется дополнительный тип тут не нужен

2022-04-14 14:14 UTC, kalyanov requested changes

2022-04-14 14:14 UTC, kalyanov commented on src/types.ts
> +    lengths: number[];
Я вообще не очень понимаю зачем массив lengths пользователю. Кажется в большинстве случаев ему нужна общая длина или периметр. 

Но если считаешь что lengths полезен, то надо добавлять его и в линию и в полигон для консистентности. При этом в линии стоит вывести общую длину в отдельном поле length, а для полигона сохранить поле периметр.

2022-04-14 14:14 UTC, kalyanov commented on src/types.ts
>  export interface ChangeEvent {
Я бы тип событие назвал просто RulerEvent оно же просто содержит стейт линейки и в нем нет никакой специфики про то что это событие изменения. В будущем такое тип можно понятным образом переиспользовать и в других событиях

2022-04-14 14:14 UTC, kalyanov commented on src/utils.ts
> +    opts: HtmlMarkerOptions,
Опасное название типа, легко спутать с опциями HTML-маркера. Давай просто в ф-е его определим, типа так
```suggestion
    opts: {
        big?: boolean;
        interactive?: boolean;
    },
```
ну и опции можно сделать необязательными, undefined, значит false

2022-04-14 14:40 UTC, kalyanov approved these changes

2022-05-25 09:54 UTC, merged