area feature
2gis/mapgl-ruler pull request #8
Opened 2022-04-13 17:00 UTC by ok-go

- функция вычисления площади
- поправил баг с обновлением дистанции точки после смены ее позиции

todo:
- настроить точку показа лейбла геометрии
- настроить стили лебла геометрии

2022-04-15 20:02 UTC, alxart commented on src/style.ts
> +    linePhase: maxPhase - 3,
Вроде, в прошлом МР хотели разделить maxPhase для HTML и WebGL объектов.

2022-04-15 20:08 UTC, alxart commented on src/geo/area.ts
> +import { GeoPoint } from '../types';
Мб создать папку utils, перенести туда папку geo и `utils.ts`?

2022-04-16 20:09 UTC, ok-go commented on src/style.ts
> +    linePhase: maxPhase - 3,
будет сделано в отдельной задаче на механизм стилизации. в тикет уже описал замечание Олега

2022-04-16 20:10 UTC, ok-go commented on src/geo/area.ts
> +import { GeoPoint } from '../types';
возможно. думаю сейчас не критично исправлять - если при добавлении нового функционала в последующих задачах понадобится, то так и сделаю

2022-04-18 04:22 UTC, alxart approved these changes

2022-04-18 06:30 UTC, kalyanov requested changes

2022-04-18 06:30 UTC, kalyanov commented on src/geo/area.ts
> +import { GeoPoint } from '../types';
давайте сразу так сделаем, если сейчас лень при создании утилит, то потом будет тем более лень, так как придется трогать код не имеющий отношения к МР

2022-04-18 06:30 UTC, kalyanov commented on jest.config.js
> +        testMatch: ['**/units/*.ts'],
```suggestion
        testMatch: ['src/test/units/**/*.ts'],
```
Раз уж решил все юниты в одну папку вытащить

2022-04-18 06:34 UTC, kalyanov commented
А чо пайпланы падают?

2022-04-18 06:35 UTC, kalyanov commented
А демку на гитхаб пэйджес когда сделаешь? :)

2022-04-18 06:41 UTC, kalyanov commented
Еще package-lock у тебя чутка протух. Выполни npm i

2022-04-18 13:04 UTC, ok-go commented
> А чо пайпланы падают?

скриншотные тесты нужно поправить

2022-04-18 13:04 UTC, ok-go commented
> Еще package-lock у тебя чутка протух. Выполни npm i

сделал - ничего не изменилось

2022-04-18 13:06 UTC, ok-go commented
> А демку на гитхаб пэйджес когда сделаешь? :)

Завел тикет

2022-04-21 04:00 UTC, kalyanov approved these changes

2022-04-21 04:00 UTC, merged